[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bevy.workspace = true
bevy_simple_tilemap.workspace = true
ron.workspace = true
serde.workspace = true
shared = { path = "../shared" }
