on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0
      - name: checkout code
        uses: actions/checkout@v4
      - name: install just
        uses: extractions/setup-just@v1
      - name: install rust
        uses: gdcorp-action-public-forks/rust-toolchain@8746a0d603bb056878fbe89fe7091bbc7aae3676
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: run rustfmt
        run: |
          just format
      - name: run clippy
        run: |
          cargo clippy
      - name: run test
        run: |
          just test-all
