on:
  pull_request:
  push:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install just
        uses: extractions/setup-just@v1
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - name: run rustfmt
        run: |
          just format

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install just
        uses: extractions/setup-just@v1
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - name: run clippy
        run: |
          cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install just
        uses: extractions/setup-just@v1
      - name: install rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
      - name: run clippy
        run: |
          just test-all

